BootStrap: docker
From: ubuntu:16.04
%setup
    # commands to be executed on host outside container during bootstrap
%files
    srmclient-2.6.28.tar.gz /opt
    voms.grid.sara.nl.lsc /home
%test
    # commands to be executed within container at close of bootstrap process
    # TODO Check whether input .proxy file is present
%post
    # commands to be executed inside container during bootstrap
    echo "deb [trusted=yes] http://repository.egi.eu/sw/production/cas/1/current egi-igtf core" >> /etc/apt/sources.list
    apt update
    apt install -y software-properties-common
    add-apt-repository 'deb http://repository.egi.eu/sw/production/cas/1/current egi-igtf core'
    apt update
    apt install -y default-jdk openjdk-8-jre-headless voms-clients ca-policy-egi-core
    cd /opt
    tar -xzf ./srmclient-2.6.28.tar.gz
    mkdir /etc/grid-security/vomsdir/lofar
    mv /home/voms.grid.sara.nl.lsc /etc/grid-security/vomsdir/lofar/voms.grid.sara.nl.lsc
%runscript
    # commands to be executed when the container runs
    export SRM_PATH=/opt/srmclient-2.6.28/usr/share/srm
    export PATH=/opt/srmclient-2.6.28/usr/bin:$PATH
    srmcp -x509_user_proxy=$1 -server_mode=passive $2 file:///$3
