kind: Service
apiVersion: v1
metadata:
  name: test-001
  namespace: cushing-001
  labels:
    app: test-001
    type: webdav
spec:
  selector:
    app: test-001
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-001
  namespace: cushing-001
  labels:
    name: test-001
spec:
  selector:
    matchLabels:
      app: test-001
  template:
    metadata:
      labels:
        app: test-001
    spec:
      hostname: test-001
      volumes:
        - name: ssh-key
          secret:
            secretName: keys
        - name: shared-data
          emptyDir:
            {}
      containers:
        - name: cocky-torvalds
          image: recap/process-sshfs:v0.1
          ports:
            - containerPort: 3001
          env:
            - name: SSH_USER
              value: cushing
            - name: SSH_HOST
              value: lisa.surfsara.nl
            - name: SSH_PORT
              value: "22"
            - name: SSH_PATH
              value: /nfs/scratch/cushing
          volumeMounts:
            - name: ssh-key
              mountPath: /ssh
              readOnly: true
            - name: shared-data
              mountPath: /shared-data
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - /bin/cat /ssh/id_rsa > /root/.ssh/id_rsa && /bin/cat
              /ssh/id_rsa.pub > /root/.ssh/id_rsa.pub  && /bin/chmod 600
              /root/.ssh/id_rsa && ssh  -o StrictHostKeyChecking=no
              $SSH_USER@$SSH_HOST ls && sshfs $SSH_USER@$SSH_HOST:$SSH_PATH
              /data && /bin/mkdir /shared-data/$SSH_HOST && cd /root/fileagent
              && node fileagent /data/ /shared-data/$SSH_HOST/ 3001
        - name: wizardly-nobel
          image: recap/process-sshfs:v0.1
          ports:
            - containerPort: 3002
          env:
            - name: SSH_USER
              value: plgcushing
            - name: SSH_HOST
              value: pro.cyfronet.pl
            - name: SSH_PORT
              value: "22"
            - name: SSH_PATH
              value: /net/archive/groups/plggprocess
          volumeMounts:
            - name: ssh-key
              mountPath: /ssh
              readOnly: true
            - name: shared-data
              mountPath: /shared-data
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - /bin/cat /ssh/id_rsa > /root/.ssh/id_rsa && /bin/cat
              /ssh/id_rsa.pub > /root/.ssh/id_rsa.pub  && /bin/chmod 600
              /root/.ssh/id_rsa && ssh  -o StrictHostKeyChecking=no
              $SSH_USER@$SSH_HOST ls && sshfs $SSH_USER@$SSH_HOST:$SSH_PATH
              /data && /bin/mkdir /shared-data/$SSH_HOST && cd /root/fileagent
              && node fileagent /data/ /shared-data/$SSH_HOST/ 3002
        - name: kind-rhodes
          image: recap/process-webdav:v0.2
          ports:
            - containerPort: 3000
          env:
            - name: AUTH_TYPE
              value: Digest
            - name: USERNAME
              value: user001
            - name: PASSWORD
              value: pass001
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - " /bin/mkdir /data/lisa.surfsara.nl && echo 'http://localhost:3001
              u p' >> /etc/davfs2/secrets && mount -t davfs
              http://localhost:3001 /data/lisa.surfsara.nl &&  /bin/mkdir
              /data/pro.cyfronet.pl && echo 'http://localhost:3002 u p' >>
              /etc/davfs2/secrets && mount -t davfs http://localhost:3002
              /data/pro.cyfronet.pl &&  cd /root/webdavserver && node
              webdavserver.js"


