apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: process-core
spec:
  selector:
    name: core-mongo
    #clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    #nodePort: 30001
    #  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: process-core
  labels:
    app: core-mongo
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: core-mongo
  namespace: process-core
  labels:
      name: core-mongo
spec:
    hostname: mongo
    nodeSelector:
        type: core
    volumes:
    - name: mongo-persistent-storage
      persistentVolumeClaim:
        claimName: mongo-pv-claim
    containers:
    - name: core-mongo
      image: mongo
      volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
            secretKeyRef:
                name: vault
                key: db-root-user
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
            secretKeyRef:
                name: vault
                key: db-root-pass
      ports:
          - containerPort: 27017
      command:
          - mongod
          - --bind_ip_all
