kind: Service
apiVersion: v1
metadata:
  name: test-001-query
  namespace: cushing-001
  labels:
    app: test-001
    type: query
spec:
  selector:
    app: test-001
  ports:
    - port: 8002
      targetPort: 8002
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: test-001-ht
  namespace: cushing-001
  labels:
    app: test-001
    type: webdav
spec:
  selector:
    app: test-001
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: test-001-jwt
  namespace: cushing-001
  labels:
    app: test-001
    type: webdav-jwt
spec:
  selector:
    app: test-001
  ports:
    - port: 8001
      targetPort: 8001
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-001
  namespace: cushing-001
  labels:
    name: test-001
spec:
  selector:
    matchLabels:
      app: test-001
  template:
    metadata:
      labels:
        app: test-001
    spec:
      hostname: test-001
      volumes:
        - name: ssh-key
          secret:
            secretName: keys
        - name: shared-data
          emptyDir:
            {}
      containers:
        - name: happy-bohr
          image: recap/process-sshfs:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: SSH_USER
              value: cushing
            - name: SSH_HOST
              value: lisa.surfsara.nl
            - name: SSH_PORT
              value: "22"
            - name: SSH_PATH
              value: /nfs/scratch/cushing
          volumeMounts:
            - name: ssh-key
              mountPath: /ssh
              readOnly: true
            - name: shared-data
              mountPath: /shared-data
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - /bin/cat /ssh/id_rsa > /root/.ssh/id_rsa && /bin/cat
              /ssh/id_rsa.pub > /root/.ssh/id_rsa.pub  && /bin/chmod 600
              /root/.ssh/id_rsa && ssh  -o StrictHostKeyChecking=no
              $SSH_USER@$SSH_HOST ls && sshfs $SSH_USER@$SSH_HOST:$SSH_PATH
              /data && /bin/mkdir /shared-data/$SSH_HOST && cd /root/fileagent
              && node fileagent /data/ /shared-data/$SSH_HOST/ 3001
        - name: eager-stallman
          image: recap/process-sshfs:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: SSH_USER
              value: plgcushing
            - name: SSH_HOST
              value: pro.cyfronet.pl
            - name: SSH_PORT
              value: "22"
            - name: SSH_PATH
              value: /net/archive/groups/plggprocess
          volumeMounts:
            - name: ssh-key
              mountPath: /ssh
              readOnly: true
            - name: shared-data
              mountPath: /shared-data
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - /bin/cat /ssh/id_rsa > /root/.ssh/id_rsa && /bin/cat
              /ssh/id_rsa.pub > /root/.ssh/id_rsa.pub  && /bin/chmod 600
              /root/.ssh/id_rsa && ssh  -o StrictHostKeyChecking=no
              $SSH_USER@$SSH_HOST ls && sshfs $SSH_USER@$SSH_HOST:$SSH_PATH
              /data && /bin/mkdir /shared-data/$SSH_HOST && cd /root/fileagent
              && node fileagent /data/ /shared-data/$SSH_HOST/ 3002
        - name: objective-perlman
          image: recap/process-core-query:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 4300
          env:
            - name: APPCONFIG
              value: W3sibmFtZSI6InByby5jeWZyb25ldC5wbCIsImhvc3QiOiJsb2NhbGhvc3QiLCJwb3J0IjozMDAyLCJ0eXBlIjoid2ViZGF2IiwibW91bnQiOiIvbmV0L2FyY2hpdmUvZ3JvdXBzL3BsZ2dwcm9jZXNzIn0seyJuYW1lIjoibGlzYS5zdXJmc2FyYS5ubCIsImhvc3QiOiJsb2NhbGhvc3QiLCJwb3J0IjozMDAxLCJ0eXBlIjoid2ViZGF2IiwibW91bnQiOiIvbmZzL3NjcmF0Y2gvY3VzaGluZyJ9XQ==
            - name: PUBLICKEY
              value: |
                -----BEGIN PUBLIC KEY-----
                MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo6JqKzZkFMCNpPyE224I
                JKKp0qGXIip4hn5r7+VONIxqV3MIvNBl3fpRLT8Zg3beIWIJQjXYmfikG6iOpWfL
                Fn2oovmKaur4l9Xb5oKWor5xHAp8lm4V19qzCcJsS0HirxVpLvR2x8s6VdtKFhGG
                z2bUpRjVGX2hfGntsQYloqGGCLAETgZoUJAzEjKlctL8iP9q3D3Zx3I9NNuY1DrS
                jXiweHn6MrKBT0CDui7FTpkuZHOs0cmaxbGBaHJ5jcmBqBg2fLKvMieAaHzX8V79
                qRJ/tOOAksAtz9O4bvbVHFlAvfuuFOatSzlKL/8uGFvn+AIyoux78F1A/aMZZvAt
                4QIDAQAB
                -----END PUBLIC KEY-----
            - name: JWTUSERS
              value: eyJyLnMuY3VzaGluZ0B1dmEubmwiOnsibmFtZSI6IlJlZ2dpZSBDdXNoaW5nIiwicHVibGljS2V5IjoiTFMwdExTMUNSVWRKVGlCUVZVSk1TVU1nUzBWWkxTMHRMUzBLVFVsSlFrbHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZQUTBGUk9FRk5TVWxDUTJkTFEwRlJSVUZ2TmtweFMzcGFhMFpOUTA1d1VIbEZNakkwU1FwS1MwdHdNSEZIV0VscGNEUm9ialZ5Tnl0V1QwNUplSEZXTTAxSmRrNUNiRE5tY0ZKTVZEaGFaek5pWlVsWFNVcFJhbGhaYldacGEwYzJhVTl3VjJaTUNrWnVNbTl2ZG0xTFlYVnlOR3c1V0dJMWIwdFhiM0kxZUVoQmNEaHNiVFJXTVRseGVrTmpTbk5UTUVocGNuaFdjRXgyVWpKNE9ITTJWbVIwUzBab1IwY0tlakppVlhCU2FsWkhXREpvWmtkdWRITlJXV3h2Y1VkSFEweEJSVlJuV205VlNrRjZSV3BMYkdOMFREaHBVRGx4TTBRelduZ3pTVGxPVG5WWk1VUnlVd3BxV0dsM1pVaHVOazF5UzBKVU1FTkVkV2szUmxSd2EzVmFTRTl6TUdOdFlYaGlSMEpoU0VvMWFtTnRRbkZDWnpKbVRFdDJUV2xsUVdGSWVsZzRWamM1Q25GU1NpOTBUMDlCYTNOQmRIbzVUelJpZG1KV1NFWnNRWFptZFhWR1QyRjBVM3BzUzB3dk9IVkhSblp1SzBGSmVXOTFlRGM0UmpGQkwyRk5XbHAyUVhRS05GRkpSRUZSUVVJS0xTMHRMUzFGVGtRZ1VGVkNURWxESUV0RldTMHRMUzB0Q2c9PSJ9fQ==
          command:
            - /bin/sh
            - -c
          args:
            - echo $JWTUSERS | base64 -d > /assets/jwtusers && echo $PUBLICKEY >
              /tmp/publicKey.txt && cd /app/ && node app.js --config $APPCONFIG
              -c /tmp/publicKey.txt -p 8002
        - name: xenodochial-germain
          image: recap/process-webdav:v0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: HTDIGEST
              value: user:jsdav:98896c65e2912eb180e87a1c1955e16a
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - " echo $HTDIGEST > /assets/htusers && /bin/mkdir
              /data/lisa.surfsara.nl && echo 'http://localhost:3001 u p' >>
              /etc/davfs2/secrets && mount -t davfs http://localhost:3001
              /data/lisa.surfsara.nl &&  echo $HTDIGEST > /assets/htusers &&
              /bin/mkdir /data/pro.cyfronet.pl && echo 'http://localhost:3002 u
              p' >> /etc/davfs2/secrets && mount -t davfs http://localhost:3002
              /data/pro.cyfronet.pl &&  cd /root/webdavserver && node
              webdavserver-ht.js"
        - name: brave-raman
          image: recap/process-webdav:v0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: JWTUSERS
              value: eyJyLnMuY3VzaGluZ0B1dmEubmwiOnsibmFtZSI6IlJlZ2dpZSBDdXNoaW5nIiwicHVibGljS2V5IjoiTFMwdExTMUNSVWRKVGlCUVZVSk1TVU1nUzBWWkxTMHRMUzBLVFVsSlFrbHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZQUTBGUk9FRk5TVWxDUTJkTFEwRlJSVUZ2TmtweFMzcGFhMFpOUTA1d1VIbEZNakkwU1FwS1MwdHdNSEZIV0VscGNEUm9ialZ5Tnl0V1QwNUplSEZXTTAxSmRrNUNiRE5tY0ZKTVZEaGFaek5pWlVsWFNVcFJhbGhaYldacGEwYzJhVTl3VjJaTUNrWnVNbTl2ZG0xTFlYVnlOR3c1V0dJMWIwdFhiM0kxZUVoQmNEaHNiVFJXTVRseGVrTmpTbk5UTUVocGNuaFdjRXgyVWpKNE9ITTJWbVIwUzBab1IwY0tlakppVlhCU2FsWkhXREpvWmtkdWRITlJXV3h2Y1VkSFEweEJSVlJuV205VlNrRjZSV3BMYkdOMFREaHBVRGx4TTBRelduZ3pTVGxPVG5WWk1VUnlVd3BxV0dsM1pVaHVOazF5UzBKVU1FTkVkV2szUmxSd2EzVmFTRTl6TUdOdFlYaGlSMEpoU0VvMWFtTnRRbkZDWnpKbVRFdDJUV2xsUVdGSWVsZzRWamM1Q25GU1NpOTBUMDlCYTNOQmRIbzVUelJpZG1KV1NFWnNRWFptZFhWR1QyRjBVM3BzUzB3dk9IVkhSblp1SzBGSmVXOTFlRGM0UmpGQkwyRk5XbHAyUVhRS05GRkpSRUZSUVVJS0xTMHRMUzFGVGtRZ1VGVkNURWxESUV0RldTMHRMUzB0Q2c9PSJ9fQ==
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - " echo $JWTUSERS | base64 -d > /assets/jwtusers && /bin/mkdir
              /data/lisa.surfsara.nl && echo 'http://localhost:3001 u p' >>
              /etc/davfs2/secrets && mount -t davfs http://localhost:3001
              /data/lisa.surfsara.nl &&  echo $JWTUSERS | base64 -d >
              /assets/jwtusers && /bin/mkdir /data/pro.cyfronet.pl && echo
              'http://localhost:3002 u p' >> /etc/davfs2/secrets && mount -t
              davfs http://localhost:3002 /data/pro.cyfronet.pl &&  cd
              /root/webdavserver && node webdavserver-jwt.js"
