kind: Service
apiVersion: v1
metadata:
  name: test-001-query
  namespace: cushing-001
  labels:
    app: test-001
    type: query
spec:
  selector:
    app: test-001
  ports:
    - port: 8002
      targetPort: 8002
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: test-001-ht
  namespace: cushing-001
  labels:
    app: test-001
    type: webdav
spec:
  selector:
    app: test-001
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: test-001-jwt
  namespace: cushing-001
  labels:
    app: test-001
    type: webdav-jwt
spec:
  selector:
    app: test-001
  ports:
    - port: 8001
      targetPort: 8001
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-001
  namespace: cushing-001
  labels:
    name: test-001
spec:
  selector:
    matchLabels:
      app: test-001
  template:
    metadata:
      labels:
        app: test-001
    spec:
      hostname: test-001
      volumes:
        - name: ssh-key
          secret:
            secretName: keys
        - name: shared-data
          emptyDir:
            {}
      containers:
        - name: competent-mestorf
          image: recap/process-sshfs:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: STORAGE_NAME
              value: mynativestorage
            - name: NAME
              value: mynativestorage
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data
          command:
            - /bin/sh
            - -c
          args:
            - /bin/mkdir -p /shared-data/$STORAGE_NAME && cd /root/fileagent &&
              node fileagent /data/ 3001
        - name: vigorous-bhaskara
          image: recap/process-sshfs:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: SSH_USER
              value: cushing
            - name: SSH_HOST
              value: lisa.surfsara.nl
            - name: SSH_PORT
              value: "22"
            - name: SSH_PATH
              value: /nfs/scratch/cushing
            - name: NAME
              value: null
          volumeMounts:
            - name: ssh-key
              mountPath: /ssh
              readOnly: true
            - name: shared-data
              mountPath: /shared-data
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - /bin/cat /ssh/id_rsa > /root/.ssh/id_rsa && /bin/cat
              /ssh/id_rsa.pub > /root/.ssh/id_rsa.pub  && /bin/chmod 600
              /root/.ssh/id_rsa && ssh  -o StrictHostKeyChecking=no
              $SSH_USER@$SSH_HOST ls && sshfs $SSH_USER@$SSH_HOST:$SSH_PATH
              /data && /bin/mkdir -p /shared-data/$SSH_HOST && cd /root/fileagent
              && node fileagent /data/ /shared-data/$SSH_HOST/ 3001
        - name: gracious-cannon
          image: recap/process-sshfs:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: SSH_USER
              value: plgcushing
            - name: SSH_HOST
              value: pro.cyfronet.pl
            - name: SSH_PORT
              value: "22"
            - name: SSH_PATH
              value: /net/archive/groups/plggprocess
            - name: NAME
              value: null
          volumeMounts:
            - name: ssh-key
              mountPath: /ssh
              readOnly: true
            - name: shared-data
              mountPath: /shared-data
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - /bin/cat /ssh/id_rsa > /root/.ssh/id_rsa && /bin/cat
              /ssh/id_rsa.pub > /root/.ssh/id_rsa.pub  && /bin/chmod 600
              /root/.ssh/id_rsa && ssh  -o StrictHostKeyChecking=no
              $SSH_USER@$SSH_HOST ls && sshfs $SSH_USER@$SSH_HOST:$SSH_PATH
              /data && /bin/mkdir -p /shared-data/$SSH_HOST && cd /root/fileagent
              && node fileagent /data/ /shared-data/$SSH_HOST/ 3002
        - name: naughty-varahamihira
          image: recap/process-core-query:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 4300
          env:
            - name: APPCONFIG
              value: W3sibmFtZSI6Imxpc2Euc3VyZnNhcmEubmwiLCJob3N0IjoibG9jYWxob3N0IiwicG9ydCI6MzAwMSwidHlwZSI6IndlYmRhdiIsIm1vdW50IjoiL25mcy9zY3JhdGNoL2N1c2hpbmcifSx7Im5hbWUiOiJwcm8uY3lmcm9uZXQucGwiLCJob3N0IjoibG9jYWxob3N0IiwicG9ydCI6MzAwMiwidHlwZSI6IndlYmRhdiIsIm1vdW50IjoiL25ldC9hcmNoaXZlL2dyb3Vwcy9wbGdncHJvY2VzcyJ9XQ==
            - name: PUBLICKEY
              value: |
                -----BEGIN PUBLIC KEY-----
                MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo6JqKzZkFMCNpPyE224I
                JKKp0qGXIip4hn5r7+VONIxqV3MIvNBl3fpRLT8Zg3beIWIJQjXYmfikG6iOpWfL
                Fn2oovmKaur4l9Xb5oKWor5xHAp8lm4V19qzCcJsS0HirxVpLvR2x8s6VdtKFhGG
                z2bUpRjVGX2hfGntsQYloqGGCLAETgZoUJAzEjKlctL8iP9q3D3Zx3I9NNuY1DrS
                jXiweHn6MrKBT0CDui7FTpkuZHOs0cmaxbGBaHJ5jcmBqBg2fLKvMieAaHzX8V79
                qRJ/tOOAksAtz9O4bvbVHFlAvfuuFOatSzlKL/8uGFvn+AIyoux78F1A/aMZZvAt
                4QIDAQAB
                -----END PUBLIC KEY-----
            - name: JWTUSERS
              value: eyJyLnMuY3VzaGluZ0B1dmEubmwiOnsicHVibGljS2V5IjoiTFMwdExTMUNSVWRKVGlCU1UwRWdVRlZDVEVsRElFdEZXUzB0TFMwdENrMUpTVUpEWjB0RFFWRkZRWFJyU3pKQ1YyUkJhVzExV1ZkR2JIWkRVRUppSzJaMk9HdzJWRkpvYW5jcmQxaFZVbWcxT0RaeVZDOUxXRUZ1YzBsc01rTXJWRWROZDFCRlpBcDRkR0pZTUhkTlVIWktNMmxIY2pCSFdXVTJWVFZaYWtONWVFUk9UV1ZyVDBoS05YaHBTMHN3WVc1RVVuUkhWRlZDVG5ObGJsaDBjM1I0Tm5CRmJISlBWR1YwZUZsc00wRUtTMGMxYTBwNFZWZEhSbE5tYlRKNFZ6UmFaR3RwVEhndlkyNWxVbFY2U2s1UWVVOURWemxRUzJFME5YUkVkVTVQVFVKQ2Qwc3pkWEZNVm5jMGNFaE1SelJIZVRsc2VXWjBDbFZzVEVKUlpuUkpOVFZ2WnpWcmRHTTVSMjVsWTBoQ00xbHhjMUJWYTFGM1ZrUTJjMGxuVGswdlQwSm1NRkZTTkhVdlZEWktabkJWWW5oeFozWmtjMkZ2WWs5aFlqRXdOZ3BCY3pVNVNIZHdRMGxzU21Nd05VbDRXRU5RVVVreVZuVlZWRzlVZHpsTmVGVlJWekp0WVhCSFV5OXdXV1ZhSzAxNlYwbG9NbXhuTDA1Q01tMUNXRlZ4TjNkSlJFRlJRVUlLTFMwdExTMUZUa1FnVWxOQklGQlZRa3hKUXlCTFJWa3RMUzB0TFFvPSJ9fQ==
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data
          command:
            - /bin/sh
            - -c
          args:
            - echo $JWTUSERS | base64 -d > /assets/jwtusers.json && echo
              $PUBLICKEY > /tmp/publicKey.txt && cd /app/ && node app.js
              --config $APPCONFIG -c /tmp/publicKey.txt -p 8002 -u
              /assets/jwtusers.json
        - name: gracious-shtern
          image: recap/process-webdav:v0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: HTDIGEST
              value: user:jsdav:98896c65e2912eb180e87a1c1955e16a
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - " echo $HTDIGEST > /assets/htusers && /bin/mkdir -p
              /data/mynativestorage && echo 'http://localhost:3001 u p' >>
              /etc/davfs2/secrets && mount -t davfs http://localhost:3001
              /data/mynativestorage &&  echo $HTDIGEST > /assets/htusers &&
              /bin/mkdir /data/undefined && echo 'http://localhost:3001 u p' >>
              /etc/davfs2/secrets && mount -t davfs http://localhost:3001
              /data/undefined &&  echo $HTDIGEST > /assets/htusers && /bin/mkdir
              /data/undefined && echo 'http://localhost:3002 u p' >>
              /etc/davfs2/secrets && mount -t davfs http://localhost:3002
              /data/undefined &&  cd /root/webdavserver && node
              webdavserver-ht.js"
        - name: hungry-kirch
          image: recap/process-webdav:v0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: JWTUSERS
              value: eyJyLnMuY3VzaGluZ0B1dmEubmwiOnsicHVibGljS2V5IjoiTFMwdExTMUNSVWRKVGlCU1UwRWdVRlZDVEVsRElFdEZXUzB0TFMwdENrMUpTVUpEWjB0RFFWRkZRWFJyU3pKQ1YyUkJhVzExV1ZkR2JIWkRVRUppSzJaMk9HdzJWRkpvYW5jcmQxaFZVbWcxT0RaeVZDOUxXRUZ1YzBsc01rTXJWRWROZDFCRlpBcDRkR0pZTUhkTlVIWktNMmxIY2pCSFdXVTJWVFZaYWtONWVFUk9UV1ZyVDBoS05YaHBTMHN3WVc1RVVuUkhWRlZDVG5ObGJsaDBjM1I0Tm5CRmJISlBWR1YwZUZsc00wRUtTMGMxYTBwNFZWZEhSbE5tYlRKNFZ6UmFaR3RwVEhndlkyNWxVbFY2U2s1UWVVOURWemxRUzJFME5YUkVkVTVQVFVKQ2Qwc3pkWEZNVm5jMGNFaE1SelJIZVRsc2VXWjBDbFZzVEVKUlpuUkpOVFZ2WnpWcmRHTTVSMjVsWTBoQ00xbHhjMUJWYTFGM1ZrUTJjMGxuVGswdlQwSm1NRkZTTkhVdlZEWktabkJWWW5oeFozWmtjMkZ2WWs5aFlqRXdOZ3BCY3pVNVNIZHdRMGxzU21Nd05VbDRXRU5RVVVreVZuVlZWRzlVZHpsTmVGVlJWekp0WVhCSFV5OXdXV1ZhSzAxNlYwbG9NbXhuTDA1Q01tMUNXRlZ4TjNkSlJFRlJRVUlLTFMwdExTMUZUa1FnVWxOQklGQlZRa3hKUXlCTFJWa3RMUzB0TFFvPSJ9fQ==
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - " echo $JWTUSERS | base64 -d > /assets/jwtusers && /bin/mkdir
              /data/mynativestorage && echo 'http://localhost:3001 u p' >>
              /etc/davfs2/secrets && mount -t davfs http://localhost:3001
              /data/mynativestorage &&  echo $JWTUSERS | base64 -d >
              /assets/jwtusers && /bin/mkdir /data/undefined && echo
              'http://localhost:3001 u p' >> /etc/davfs2/secrets && mount -t
              davfs http://localhost:3001 /data/undefined &&  echo $JWTUSERS |
              base64 -d > /assets/jwtusers && /bin/mkdir /data/undefined && echo
              'http://localhost:3002 u p' >> /etc/davfs2/secrets && mount -t
              davfs http://localhost:3002 /data/undefined &&  cd
              /root/webdavserver && node webdavserver-jwt.js"
