BootStrap: docker
From: ubuntu:16.04
%setup
   # commands to be executed on host outside container during bootstrap
   cp ./requirements $SINGULARITY_ROOTFS
%test
   # commands to be executed within container at close of bootstrap process
   exec /usr/bin/python --version
%runscript
   # commands to be executed when the container runs
   echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
   echo "PATH: $PATH"
   echo "Arguments received: $*"
   exec /usr/bin/python "$@"
%post
   # commands to be executed inside container during bootstrap
   apt-get update && apt-get install -y \
        python-pip \
        vim \
        python-dev \
        pkg-config \
        libopencv-dev \
        libav-tools  \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libjasper-dev \
        build-essential \
        openslide-tools \
        cmake \
        git \
        libgtk2.0-dev \
        pkg-config \
        libavcodec-dev \
        libavformat-dev \
        libswscale-dev \
        libcurl4-gnutls-dev \
        librtmp-dev

   pip install --upgrade pip
   python -m pip install -r /requirements
