FROM ubuntu:18.04
RUN apt-get update && apt-get install -y singularity-container
#RUN mkdir /assets
#RUN mkdir /shared-data
#ADD src/app.js /app/
#ADD src/index.html /app/
#ADD src/package.json /app/
#WORKDIR /app
#RUN npm install
